name: Node.js CI

on:
  push:
    paths:
      - 'packages/vite-plugin-styled-windicss/**'
    branches: [master]
  pull_request:
    paths:
      - 'packages/vite-plugin-styled-windicss/**'
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Styled Windicss

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        working-directory: ./packages/vite-plugin-styled-windicss
        run: |
          yarn
          yarn build
